export const GETCATEGORY = "GETCATEGORY" //replace name to read category
export const CREATEECATEGORY = "CREATEECATEGORY"
export const UPADATECATEGORY = "UPADATECATEGORY"
export const DELETECATEGORY = "DELETECATEGORY"